services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: irep
    ports:
      - "8090:8080"
      - "8091:8000"
    volumes:
      - .:/workspace/irep
      - ./storage/logs:/workspace/irep/storage/logs
    env_file:
      - .env
    environment:
      DB_HOST: database
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  database:
    image: mariadb:latest
    container_name: irepDB
    ports:
      - "2209:3306"
    env_file:
      - docker/database.env
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - network
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      retries: 3
      start_period: 30s
      timeout: 10s

  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    ports:
      - "7709:7700"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - msdata:/data.ms
      - ./docker/meilisearch/config.toml:/meilisearch_config.toml
    networks:
      - network
    restart: always
    command: ["meilisearch", "--config-file-path", "/meilisearch_config.toml"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  dbdata:
  msdata:

networks:
  network:
    driver: bridge

