swagger: '2.0'
info:
  version: 0.0.1
  title: 'iRep API'
  description: |
    <h1>This is a Restful API for the `states_local_govt` Database. </h1>
    <h3>It is built on the flexible PHP SLIM framework and Swagger, which was 
        used to generate this Documentation
    </h3>
    <h4>Although the content of this documentation is assumed to be self 
        explanatory, and the API easy to consume, 
        You can send an email to [company email here] for help/support
    </h4>
host: irep.azurewebsites.net
basePath: /
paths:
  /auth/State:
    get:
      description: |
        Gets `State` objects.
        A ***State Object*** is 
        complete list of all the columns in
        the `states` table of the `states_local_govt` database
      parameters:
        - name: id
          in: query
          description: ID number of a particular `state object`
          required: false
          type: number
          format: int
      responses:
        '200':
          description: Successful response
          schema:
            title: getState
            type: object
            items:
              title: id_no
              type: number
              properties:
                name: 
                  type: number
                single:
                  type: integer
  /auth/FederalConstituency:
    get:
      description: |
        Gets a `Federal Consituency` objects.
        A ***Federal Constituency Object*** is 
        complete list of all the columns in
        the `federal_consituency` table of the `states_local_govt` database
      parameters:
        - name: id
          in: query
          description: ID number of a particular `federal consituency object`
          required: false
          type: number
          format: int
      responses:
        '200':
          description: Successful response
          schema:
            title: getFederalConstituency
            type: object
            items:
              title: id_no
              type: number
              properties:
                name: 
                  type: number
                single:
                  type: integer
  /auth/StateConstituency:
    get:
      description: |
        Gets a `State Consituency` objects.
        A ***State Constituency Object*** is 
        complete list of all the columns in
        the `state_constituencies` table of the `states_local_govt` database
      parameters:
        - name: id
          in: query
          description: ID number of a particular `state consituency object`
          required: false
          type: number
          format: int
      responses:
        '200':
          description: Successful response
          schema:
            title: getStateConstituency
            type: object
            items:
              title: id_no
              type: number
              properties:
                name: 
                  type: number
                single:
                  type: integer
  /auth/LocalGovernment:
    get:
      description: |
        Gets a `Local Government` objects.
        A ***Local Government Object*** is 
        complete list of all the columns in
        the `local_govt` table of the `states_local_govt` database
      parameters:
        - name: id
          in: query
          description: ID number of a particular `local government object`
          required: false
          type: number
          format: int
      responses:
        '200':
          description: Successful response
          schema:
            title: getLocalGovernment
            type: object
            items:
              title: id_no
              type: number
              properties:
                name: 
                  type: number
                single:
                  type: integer
  /auth/SenatorialDistrict:
    get:
      description: |
        Gets a `Senatorial District` objects.
        A ***Senatorial District Object*** is 
        complete list of all the columns in
        the `senatorial_districts` table of the `states_local_govt` database
      parameters:
        - name: id
          in: query
          description: ID number of a particular `senatorial district object`
          required: false
          type: number
          format: int
      responses:
        '200':
          description: Successful response
          schema:
            title: getSenatorialDistrict
            type: object
            items:
              title: id_no
              type: number
              properties:
                name: 
                  type: number
                single:
                  type: integer